FROM centos:latest

LABEL email="nikolai.bondar@gmail.com"

ENV status="First Dockerfile"
ENV date="12.08.2022"

#RUN apk update && apk install net-tools -y && apk install python3 -y

COPY . ./files

CMD ["sh", "descr.sh"]
CMD ["sh", "find.sh"]

VOLUME /devops_volume